### ISSUE TITLE
CppSide server exits after receiving mode command from PySide

### ISSUE THREAD

**Issue by skwerlman** [gooday2die/AllPeripherals#1]
Version: 1.1.1 x64

CppSide log:
```
PS C:\Users\user\Apps\allperif\cppSide> .\AllPheriperalCPP.exe
                                                                             Windows 64bit C++ Side Program
                                                                                              by Gooday2die
                                       Please Check My Github : https://github.com/gooday2die/AllPeripherals
[Wrapper] Initializng all SDK wrappers...
[Corsair] Successfully Requested Control
[Corsair] Total Connected Devices : 3
[Corsair] Keyboard : STRAFE RGB
[Corsair] Mouse : GLAIVE RGB
[Corsair] Cooler : H100i PRO
[Corsair] Dumped Files to RAM
[Corsair] Initialization Process Complete
[Razer] Failed to initialize Razer Chroma SDK
[Razer] Successfully initialized Razer Chroma SDK
[Razer] Finished detecting Razer devices.
[Wrapper] Using Corsair SDK
[Server] Now initializing socket server...
[Server] Client was successfully connected.
[Server] Operating program in mode 1
[Server] Now syncing all the colors
[Server] Received Mode 1 : Screen Reactive
[Server] Now syncing all colors
PS C:\Users\user\Apps\allperif\cppSide>
```

PySide log:
```
PS C:\Users\user\Apps\allperif\pythonSide> python .\main.py -operationmode 1
[False, 0, 0]
 █████╗ ██╗     ██╗     ██████╗ ███████╗██████╗ ██╗██████╗ ██╗  ██╗███████╗██████╗  █████╗ ██╗     ███████╗
██╔══██╗██║     ██║     ██╔══██╗██╔════╝██╔══██╗██║██╔══██╗██║  ██║██╔════╝██╔══██╗██╔══██╗██║     ██╔════╝
███████║██║     ██║     ██████╔╝█████╗  ██████╔╝██║██████╔╝███████║█████╗  ██████╔╝███████║██║     ███████╗
██╔══██║██║     ██║     ██╔═══╝ ██╔══╝  ██╔══██╗██║██╔═══╝ ██╔══██║██╔══╝  ██╔══██╗██╔══██║██║     ╚════██║
██║  ██║███████╗███████╗██║     ███████╗██║  ██║██║██║     ██║  ██║███████╗██║  ██║██║  ██║███████╗███████║
╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝
                                                                                WindowsOS PythonSide Script
                                                                                              By Gooday2die
                                      Please Check My Github : https://github.com/gooday2die/AllPeripherals
Please Select Operation Mode
1 ScreenReactive
2 RainbowAll
Mode : 1
[OperationMode] Set Operation Mode 1 : Screen Reactive
[Client] Connecting to port : 37716
[Client] Sent operation mode : 1

[ScreenReactive] Mode Initialized. Delay : 0
Traceback (most recent call last):
  File ".\main.py", line 161, in <module>
    screen_reactive()
  File ".\main.py", line 107, in screen_reactive
    bridge_obj.send_rgb_value(rgb_list[0], rgb_list[1], rgb_list[2])
  File "C:\Users\user\Apps\allperif\pythonSide\Bridge.py", line 63, in send_rgb_value
    self.client_sock.send(send_byte)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
PS C:\Users\user\Apps\allperif\pythonSide>
```

**Comment by hunter-goller** [comment]
I am getting this exact error too.
C:\Users\footb>cd C:\Users\footb\Downloads\icue_lighting_python\x64\cppSide

C:\Users\footb\Downloads\icue_lighting_python\x64\cppSide>run AllPheriperalCPP.exe
'run' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\footb\Downloads\icue_lighting_python\x64\cppSide>staRT AllPheriperalCPP.exe

C:\Users\footb\Downloads\icue_lighting_python\x64\cppSide>CD C:\Users\footb\Downloads\icue_lighting_python\x64\pythonSide

C:\Users\footb\Downloads\icue_lighting_python\x64\pythonSide>py main.py
[False, 0, 0]
 █████╗ ██╗     ██╗     ██████╗ ███████╗██████╗ ██╗██████╗ ██╗  ██╗███████╗██████╗  █████╗ ██╗     ███████╗
██╔══██╗██║     ██║     ██╔══██╗██╔════╝██╔══██╗██║██╔══██╗██║  ██║██╔════╝██╔══██╗██╔══██╗██║     ██╔════╝
███████║██║     ██║     ██████╔╝█████╗  ██████╔╝██║██████╔╝███████║█████╗  ██████╔╝███████║██║     ███████╗
██╔══██║██║     ██║     ██╔═══╝ ██╔══╝  ██╔══██╗██║██╔═══╝ ██╔══██║██╔══╝  ██╔══██╗██╔══██║██║     ╚════██║
██║  ██║███████╗███████╗██║     ███████╗██║  ██║██║██║     ██║  ██║███████╗██║  ██║██║  ██║███████╗███████║
╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝
                                                                                WindowsOS PythonSide Script
                                                                                              By Gooday2die
                                      Please Check My Github : https://github.com/gooday2die/AllPeripherals
Please Select Operation Mode
1 ScreenReactive
2 RainbowAll
Mode : 1
[OperationMode] Set Operation Mode 1 : Screen Reactive
[Client] Connecting to port : 37716
[Client] Sent operation mode : 1

[ScreenReactive] Mode Initialized. Delay : 0
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    screen_reactive()
  File "main.py", line 107, in screen_reactive
    bridge_obj.send_rgb_value(rgb_list[0], rgb_list[1], rgb_list[2])
  File "C:\Users\footb\Downloads\icue_lighting_python\x64\pythonSide\Bridge.py", line 63, in send_rgb_value
    self.client_sock.send(send_byte)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by hunter-goller** [comment]
Side Program
                                                                                              by Gooday2die
                                       Please Check My Github : https://github.com/gooday2dieAllPeripherals
[Wrapper] Initializng all SDK wrappers...
[Corsair] Successfully Requested Control
[Corsair] Total Connected Devices : 2
[Corsair] LightingNodePro : Lighting Node CORE
[Corsair] Cooler : H100i PLATINUM
[Corsair] Dumped Files to RAM
[Corsair] Initialization Process Complete
[Razer] Failed to initialize Razer Chroma SDK
[Razer] Successfully initialized Razer Chroma SDK
[Razer] Finished detecting Razer devices.
[Wrapper] Using Corsair SDK
[Server] Now initializing socket server...

**Comment by isu-kim** [comment]
Hello, It had been long time I had not updated this project.
I had some personal issues and now I am back.
This project is kind of outdated right now, so please check
[pyrgbdev](https://github.com/gooday2die/PyRGBDev) which is my new library that does the same thing easily!
Thank you for your interest in my project!
