### ISSUE TITLE
CUESDK for Python is available

### ISSUE THREAD

**Issue by intrueder** [gooday2die/AllPeripherals#2]
> Since all the SDKs provided by the official manufacturers support mainly C++ or C#

I'm here to tell you about cue-sdk for python https://github.com/CorsairOfficial/cue-sdk-python 😉 

Also, you probably want to check what's new in recent CUESDK releases: https://github.com/CorsairOfficial/cue-sdk/releases

**Comment by isu-kim** [comment]
Thank you for your information. I have checked the library and made a package named [pyrgbdev](https://github.com/gooday2die/PyRGBDev). This AllPeripherals is depreciated and outdated, so please check the new project out. Thanks!
